---
- name: Update and Install packages
  hosts: localhost
  become: true
  tasks:
    - name: upgrade all packages
      package:
          name: "*"
          state: latest

    - name: install git, vim, docker, ansible, python3, python3-pip
      package:
        name = {{ item }}
        state = present
      with_items:
        - git
        - vim
        - docker
        - ansible
        - python3
        - build-essential

- name: Download Vim Cfg
  hosts: localhost
  tasks:
    - name: create directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - { ~/.vim/bundle }
        - { ~/.vim/autoload }

    - name: download vim cfg from github
      git:
        repo: https://github.com/jdeck002/dotvim.git
        dest: ~/.vim
    - name: create .vimrc symlink
      file:
        src: '~/.vim/.vimrc'
        dest: '~/.vimrc'
        state: link
...
