---
- name: Update and Install packages
  hosts: localhost
  become: true
  tasks:
    - name: upgrade all packages
      package:
          name: "*"
          state: latest

    - name: install git, neovim, docker, ansible, python3, python3-pip, build-essential
      package:
        name = {{ item }}
        state = present
      with_items:
        - git
        - neovim
        - docker
        - ansible
        - python3
        - build-essential
        - python3-pip
        - tilix

- name: Download Vim Cfg
  hosts: localhost
  tasks:
    - name: download dotfiles from github
      git:
        repo: https://github.com/jdeck002/dotfiles.git
        dest: ~/.dotfiles
    - name: create nvim init symlinks
      file:
        src: '~/.dotfiles/init.vim'
        dest: '~/.config/nvim/.init.vim'
        state: link
    - name: create nvim coc-settings simlink
      file:
        src: '~/.dotfiles/coc-settings.json'
        dest: '~/.config/nvim/coc-settings.json'
        state: link
    - name: create .bashrc symlink
      file:
        src: '~/.dotfiles/.bashrc'
        dest: '~/.bashrc'
        state: link
...
