---
- name: Update and Install packages
  hosts: localhost
  become: true
  tasks:
    - name: upgrade all packages
      package:
          name: "*"
          state: latest

    - name: install git, vim, docker, ansible
      package:
        name = {{ item }}
        state = present
      with_items:
        - git
        - vim
        - docker
        - ansible

- name: Download Vim Cfg
  hosts: localhost
  tasks:
    - name: download vim cfg from github
      git:
        repo: git@github.com:jdeck002/dotvim.git
        dest: ~/.vim
    - name: create .vimrc symlink
      file:
        src: '~/.vim/.vimrc'
        dest: '~/.vimrc'
        state: link
...
